image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'yarn && yarn build'
    command: 'yarn watch'
ports:
  - port: 8080
    onOpen: open-preview  
vscode:
  extensions:
    - octref.vetur@0.23.0:TEzauMObB6f3i2JqlvrOpA==
